### PR TITLE
Use SPDX identifier for licence

### PR DESCRIPTION
**Pull request by ndevenish**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] ~~Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This prevents conda-forge bots from complaining about the licence specifier being in an unknown form.

Also, using this issue as a trigger for re-rendering.

### CODE REVIEW

**Comment by ndevenish** [comment]
@conda-forge-admin, please rerender

**Comment by mcs07** [comment]
If this isn't fixed in the gtest feedstock any time soon, could adding `gmock` as a test `requires` work as a quick fix?

**Comment by ndevenish** [comment]
Yes, I was hoping it could be fixed upstream rather than working around it here. Maybe it's better to be practical than pure.

**Comment by mcs07** [comment]
@ndevenish would you like to add yourself as a maintainer?

**Comment by ndevenish** [comment]
Happy to. I assume you are okay with merging this when the CI clears then?

**Pull request merged**
