### PR TITLE
Remove @mcs07 as maintainer

### PR DESCRIPTION
**Pull request by mcs07**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by mcs07** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
does ci-skip work? i feel like i saw the compilers change, so i decided to bump the build number.

**Comment by hmaarrfk** [comment]
Thanks for your help!

**Comment by mcs07** [comment]
I believe `[skip ci]` would cause no build/upload after the merge. But since the rerender changed the osx compilers and you bumped the build number, I removed it.

**Pull request merged**
